export * from "./Hero";
export * from "./Statistics";
export * from "./ShowOffService";
export * from "./HomeMain";
export * from "./Pricing";
export * from "./Testimonial";
export * from "./Features";
export * from "./CallToAction";
export * from "./Footer";
